services:
  payment-portal-web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    volumes:
      - node_modules:/app/node_modules
      - ./:/app
    environment:
      JWT_SECRET: ${JWT_SECRET}

volumes:
  node_modules:
